import { connect, type Chain } from './chain.js';
import { classify } from './classify.js';
import { codeHash, deployRuntime } from './deploy.js';
import { formatDisassembly, fromHex, hex } from './opcodes.js';
import { PROBE_GAS, gasSweep, probe, standardProbes, type ProbeResult, type ProbeSpec } from './probe.js';
import { computeStats, printStats } from './report.js';
import { cryptoRng, seededRng } from './rng.js';
import { score } from './score.js';
import { loadRun, loadSpecimen, openRun, saveInteresting } from './store.js';

interface Args { [k: string]: string | boolean }
function parseArgs(argv: string[]): { cmd: string; args: Args } {
  const [cmd = 'explore', ...rest] = argv;
  const args: Args = {};
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (a.startsWith('--')) {
      const k = a.slice(2), v = rest[i + 1];
      if (v !== undefined && !v.startsWith('--')) { args[k] = v; i++; } else args[k] = true;
    }
  }
  return { cmd, args };
}

const fmt = (n: number) => n.toLocaleString('en-US');
const RULE = '────────────────────────────────────────';
const OOG_CEILINGS = [100_000, 1_000_000, 10_000_000];

/** Everything we do to one specimen, given its bytecode and probe payloads. */
async function examine(chain: Chain, runtime: Uint8Array, payloads: { random32: Uint8Array; selector: Uint8Array; arg32: Uint8Array }, probesWanted: string[]) {
  const birth = await deployRuntime(chain, runtime);
  const born = birth.status === 'deployed';
  const probes: ProbeResult[] = [];
  let oog: any[] | undefined;
  if (born && birth.address) {
    const specs = standardProbes(payloads.random32, payloads.selector, payloads.arg32).filter((s) => probesWanted.includes(s.name[0]));
    for (const spec of specs) {
      try { probes.push(await probe(chain, birth.address, spec)); }
      catch (e: any) { probes.push(errorProbe(spec, String(e.message ?? e))); }
    }
    // a program that ran until we stopped it deserves a closer look
    const oogProbe = probes.find((p) => p.outcome === 'out_of_gas');
    if (oogProbe) {
      const spec = specs.find((s) => s.name === oogProbe.name)!;
      try { oog = await gasSweep(chain, birth.address, spec, OOG_CEILINGS); }
      catch (e: any) { oog = [{ gas: 0, outcome: 'other_halt', gasUsed: 0, error: `sweep failed: ${String(e.message ?? e)}` }]; }
    }
  }
  const cls = classify(probes, born);
  const sc = score(probes, cls);
  return { birth, probes, cls, sc, oog };
}

/** The instrument itself failed on this probe; say so rather than guess. */
function errorProbe(spec: ProbeSpec, error: string): ProbeResult {
  return { name: spec.name, calldata: spec.calldata, value: spec.value.toString(), outcome: 'other_halt', error: `instrument: ${error}`, rawError: error, gasUsed: 0, returnData: '0x', returnDataLength: 0, ops: [], instructionCount: 0, opCounts: {}, maxDepth: 1, storageWrites: 0, storageReads: 0, logs: 0, calls: 0, creates: 0, keccaks: 0, jumps: 0, memoryOps: 0 };
}

function printSpecimen(id: string, bytes: number, runtime: Uint8Array, r: Awaited<ReturnType<typeof examine>>, disasm: boolean) {
  const { birth, probes, cls, sc, oog } = r;
  const born = birth.status === 'deployed';
  console.log(`SLOPWARE #${id}`);
  console.log(`STATUS       ${born ? 'INSTALLED' : 'REFUSED'}${birth.reason ? ` — ${birth.reason}` : ''}`);
  console.log(`LENGTH       ${bytes} bytes`);
  console.log(`BYTECODE     0x${hex(runtime)}`);
  console.log(`KECCAK       ${codeHash(runtime)}`);
  if (born) {
    console.log(`ADDRESS      ${birth.address}`);
    console.log(`VERIFIED     ${birth.codeMatches ? 'deployed bytes === generated bytes' : 'MISMATCH'} · placement gas ${fmt(birth.gasUsed ?? 0)}`);
  }
  if (disasm) { console.log(`DISASSEMBLY`); console.log(indent(formatDisassembly(runtime), 13)); }
  for (const p of probes) {
    console.log(RULE);
    console.log(p.name.slice(2).toUpperCase());
    console.log(`${p.outcome.toUpperCase().replace('_', ' ')}${p.rawError ? ` (${p.rawError})` : ''}`);
    console.log(`Gas supplied: ${fmt(PROBE_GAS)} · consumed: ${fmt(p.gasUsed)}${p.outcome !== 'success' && p.outcome !== 'revert' ? ' (exceptional halt: all gas is consumed)' : ''}`);
    if (p.outcome === 'success') console.log(`Return: ${p.returnDataLength} bytes${p.returnDataLength ? ` ${p.returnData}` : ''}`);
    if (p.outcome === 'revert') console.log(`Revert data: ${p.returnDataLength} bytes${p.returnDataLength ? ` ${p.returnData}` : ''}`);
    console.log(`Instructions: ${p.instructionCount}${p.maxStackDepth !== undefined ? ` · max stack ${p.maxStackDepth}` : ''}${p.maxDepth > 1 ? ` · call depth ${p.maxDepth}` : ''}`);
    console.log(`TRACE`);
    console.log(p.ops.length ? indent(p.ops.length > 40 ? [...p.ops.slice(0, 20), `… ${p.ops.length - 40} more …`, ...p.ops.slice(-20)].join('\n') : p.ops.join('\n'), 2) : '  (halted before the first instruction)');
  }
  if (oog) {
    console.log(RULE);
    console.log(`OUT OF GAS — does more gas change it?`);
    for (const g of oog) console.log(`  ${fmt(g.gas).padStart(11)} gas → ${g.outcome.toUpperCase().replace('_', ' ')} after ${fmt(g.instructions)} instructions${g.loopSignature ? ` · loop: ${g.loopSignature}` : ''}`);
  }
  console.log(RULE);
  console.log(`OBSERVED TRAITS`);
  console.log(indent(cls.traits.join('\n'), 2));
  console.log(`CLASSIFICATION`);
  console.log(`  ${cls.primary}`);
  console.log(`INTERESTINGNESS  ${sc.total}  (${Object.entries(sc.parts).map(([k, v]) => `${k} ${v > 0 ? '+' : ''}${v}`).join(', ')})`);
  if (cls.notes.length) { console.log(`NOTES`); console.log(indent(cls.notes.join('\n'), 2)); }
  console.log();
}

async function explore(args: Args) {
  const count = Number(args.count ?? 10);
  const bytes = Number(args.bytes ?? 64);
  const rpc = String(args.rpc ?? 'http://127.0.0.1:8546');
  const probesWanted = String(args.probes ?? 'ABCDE').toUpperCase().split('');
  const rng = args.seed ? seededRng(String(args.seed)) : cryptoRng();
  const disasm = Boolean(args.disasm);
  const quiet = Boolean(args.quiet);
  const workers = Math.max(1, Math.min(10, Number(args.workers ?? 8)));
  const keepTop = Number(args.top ?? 20);
  // compact: for programs that die within two instructions with no notable trait, the opcode
  // list is the first one or two opcodes of the disassembly; drop it and keep everything else
  const compact = Boolean(args.compact);

  const chains = await Promise.all(Array.from({ length: workers }, (_, i) => connect(rpc, i)));
  const runId = String(args.run ?? `${new Date().toISOString().replace(/[:.]/g, '-')}-${bytes}b-${count}${rng.seed ? `-${rng.seed}` : ''}`);
  const run = openRun({ id: runId, startedAt: new Date().toISOString(), count, bytes, mode: rng.mode, seed: rng.seed, rpc, probes: probesWanted, gasPerProbe: PROBE_GAS });

  console.log(`SLOPWARE — lab`);
  console.log(`${fmt(count)} specimens · ${bytes} bytes each · entropy ${rng.mode}${rng.seed ? ` "${rng.seed}"` : ''} · probes ${probesWanted.join('')} · ${workers} workers · run ${runId}\n`);

  // bytecode and payloads are drawn up front, in order, so a seed reproduces the run regardless of worker timing
  const jobs = Array.from({ length: count }, (_, i) => ({
    id: String(i + 1).padStart(6, '0'),
    runtime: rng.bytes(bytes),
    payloads: { random32: rng.bytes(32), selector: rng.bytes(4), arg32: rng.bytes(32) },
  }));

  const records: any[] = new Array(count);
  let next = 0, done = 0;
  const t0 = Date.now();
  await Promise.all(chains.map(async (chain) => {
    for (;;) {
      const i = next++;
      if (i >= count) return;
      const job = jobs[i];
      const r = await examine(chain, job.runtime, job.payloads, probesWanted);
      if (compact) {
        const trivial = r.probes.every((p) => p.instructionCount <= 2 && p.outcome !== 'success') && r.cls.traits.every((t) => ['INVALID_OPCODE', 'STACK_UNDERFLOW', 'DIES_AT_FIRST_INSTRUCTION', 'FUTURE_OPCODE', 'BAD_JUMP'].includes(t));
        if (trivial) for (const p of r.probes) { (p as any).ops = undefined; (p as any).opCounts = undefined; (p as any).compact = true; }
      }
      const rec = { id: job.id, bytes, bytecode: `0x${hex(job.runtime)}`, keccak: codeHash(job.runtime), birth: r.birth, probes: r.probes, oog: r.oog, classification: r.cls, score: r.sc, probePayloads: { random32: hex(job.payloads.random32), selector: hex(job.payloads.selector), arg32: hex(job.payloads.arg32) } };
      records[i] = rec;
      run.specimen(rec); // on disk immediately: a crash later loses nothing
      if (!quiet) printSpecimen(job.id, bytes, job.runtime, r, disasm);
      done++;
      if (quiet && done % 500 === 0) console.log(`  ${fmt(done)} / ${fmt(count)} · ${((Date.now() - t0) / 1000).toFixed(0)} s`);
    }
  }));

  const stats = computeStats(records, bytes);
  run.finish({ ...stats, seconds: Math.round((Date.now() - t0) / 1000) });
  const top = [...records].sort((a, b) => b.score.total - a.score.total).slice(0, keepTop);
  for (const rec of top) saveInteresting(run.dir, rec.id, rec);

  console.log(RULE);
  printStats(stats);
  console.log(`\nMOST INTERESTING`);
  for (const rec of top.slice(0, 5)) {
    const lives = rec.probes.map((p: ProbeResult) => `${p.name[0]}:${p.outcome === 'success' ? 'ok' : p.outcome.replace('_', ' ')}/${p.instructionCount}`).join(' ');
    console.log(`  #${rec.id}  score ${String(rec.score.total).padStart(5)}  ${rec.classification.primary.padEnd(16)} ${lives}  traits: ${rec.classification.traits.filter((t: string) => !['DIES_AT_FIRST_INSTRUCTION'].includes(t)).join(', ')}`);
  }
  console.log(`\n${((Date.now() - t0) / 1000).toFixed(1)} s · preserved in ${run.dir}/ · inspect: npm run inspect -- --run ${runId} --id <id>`);
}

async function inspect(args: Args) {
  const rec = loadSpecimen(String(args.run), String(args.id));
  if (!rec) throw new Error(`no specimen ${args.id} in run ${args.run}`);
  const runtime = fromHex(rec.bytecode);
  printSpecimen(rec.id, rec.bytes, runtime, { birth: rec.birth, probes: rec.probes, cls: rec.classification, sc: rec.score ?? { total: 0, parts: {} }, oog: rec.oog }, true);
  console.log(`probe payloads: random32 ${rec.probePayloads.random32} · selector ${rec.probePayloads.selector} · arg32 ${rec.probePayloads.arg32}`);
}

async function replay(args: Args) {
  const rec = loadSpecimen(String(args.run), String(args.id));
  if (!rec) throw new Error(`no specimen ${args.id} in run ${args.run}`);
  const chain = await connect(String(args.rpc ?? 'http://127.0.0.1:8546'));
  const runtime = fromHex(rec.bytecode);
  const payloads = { random32: fromHex(rec.probePayloads.random32), selector: fromHex(rec.probePayloads.selector), arg32: fromHex(rec.probePayloads.arg32) };
  const { meta } = loadRun(String(args.run));
  const r = await examine(chain, runtime, payloads, meta.probes);
  console.log(`REPLAY of #${rec.id} from run ${args.run} — placed again at a new address, same bytecode, same payloads\n`);
  printSpecimen(rec.id, rec.bytes, runtime, r, Boolean(args.disasm));
  const same = JSON.stringify(r.probes.map((p) => [p.outcome, p.instructionCount, p.returnData, p.ops])) === JSON.stringify(rec.probes.map((p: ProbeResult) => [p.outcome, p.instructionCount, p.returnData, p.ops]));
  console.log(same ? 'behaviour identical to the preserved record' : 'BEHAVIOUR DIFFERS from the preserved record (address- or block-dependent program?)');
}

function indent(s: string, n: number) { const pad = ' '.repeat(n); return s.split('\n').map((l) => pad + l).join('\n'); }

const { cmd, args } = parseArgs(process.argv.slice(2));
const run = cmd === 'explore' ? explore(args) : cmd === 'inspect' ? inspect(args) : cmd === 'replay' ? replay(args) : Promise.reject(new Error(`unknown command ${cmd}`));
run.then(() => process.exit(0)).catch((e) => { console.error(e.message ?? e); process.exit(1); });
